### ISSUE TITLE
Markdown support does not recognize tables

### ISSUE THREAD

**Issue by halindrome** [paul-j-lucas/wrap#5]
Or at least that's what I think happened.    I had input like this:

```
|Keyword        | Values          | Meaning
|---------------|-----------------|---------
|name           | string          | The name of this test for display purposes
|description    | string          | A long self-describing paragraph that explains the purpose of the test and the expected input
|ref            | URI             | An optional reference to the portion of the specification to which the test relates
|testType       | `automated`, `manual`, `ref` | The type of test - this informs [WPT](https://github.com/w3c/web-platform-tests) how the test should be controlled and presented
|assertions     | list of URI, List, or AssertionObject | The ordered collection of tests the input should be run against. See [JSON Schema Usage](#jsonSchema) for the structure of the objects.  URI is relative to the top level folder of the test collection if it has a slash; relative to the current directory if it does not. Lists can be nested to define groups of sub-tests.  Assertions / groups can be conditionally skipped.  See [Assertion Lists](#assertionLists) for more details.

```
(which on GitHub formats like):

> |Keyword        | Values          | Meaning
|---------------|-----------------|---------
|name           | string          | The name of this test for display purposes
|description    | string          | A long self-describing paragraph that explains the purpose of the test and the expected input
|ref            | URI             | An optional reference to the portion of the specification to which the test relates
|testType       | `automated`, `manual`, `ref` | The type of test - this informs [WPT](https://github.com/w3c/web-platform-tests) how the test should be controlled and presented
|assertions     | list of URI, List, or AssertionObject | The ordered collection of tests the input should be run against. See [JSON Schema Usage](#jsonSchema) for the structure of the objects.  URI is relative to the top level folder of the test collection if it has a slash; relative to the current directory if it does not. Lists can be nested to define groups of sub-tests.  Assertions / groups can be conditionally skipped.  See [Assertion Lists](#assertionLists) for more details.

and after passing it through wrap -u it looks like:

```
|Keyword | Values | Meaning |---------------|-----------------|--------- |name
| string | The name of this test for display purposes |description | string | A
long self-describing paragraph that explains the purpose of the test and the
expected input |ref | URI | An optional reference to the portion of the                                        specification to which the test relates |testType | `automated`, `manual`,
`ref` | The type of test - this informs                                                                        [WPT](https://github.com/w3c/web-platform-tests) how the test should be
controlled and presented |assertions | list of URI, List, or AssertionObject |                                 The ordered collection of tests the input should be run against. See [JSON
Schema Usage](#jsonSchema) for the structure of the objects.  URI is relative                                  to the top level folder of the test collection if it has a slash; relative to                                  the current directory if it does not. Lists can be nested to define groups of                                  sub-tests.  Assertions / groups can be conditionally skipped.  See [Assertion                                  Lists](#assertionLists) for more details.
```

**Comment by paul-j-lucas** [comment]
Tables aren't supported (otherwise it would be in the man page). It's basic Markdown plus code fences from PHP Markdown Extra.

- Paul

**Comment by paul-j-lucas** [comment]
I've just added table support.

**Comment by halindrome** [comment]
Works great!  Thanks!
