### ISSUE TITLE
Possible missing #include in options.c

### ISSUE THREAD

**Issue by larryhynes** [paul-j-lucas/wrap#6]
Hi

Thanks for your work on `wrap` - I use it all the time.

Recent git checkouts have failed to build locally for me due to "undeclared identifier" errors.

Adding `#include "unistd.h"` to `src/options.c` fixes the issue.

**Comment by paul-j-lucas** [comment]
> Thanks for your work on `wrap` - I use it all the time.

You're welcome.  (So do I.  I wrote it to "scratch an itch.")

> Recent git checkouts have failed to build locally for me due to "undeclared identifier" errors.

Should be fixed.

> Adding `#include "unistd.h"` to `src/options.c` fixes the issue.

Actually, `#include <unistd.h>`.
